# -*- coding: utf-8 -*-
"""fetch_sinan_base_territorio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZytWF2sFprapHj8aThjFifqgSy2eukfV
"""

#carregando bibliotecas

!pip install pysus
pip install pandas pathlib
import pandas as pd
from pathlib import Path
from pysus import SINAN
from pysus.online_data import territory

pip install pysus pandas pathlib

# criando classe sinan para executar os métodos
sinan = SINAN().load() # Loads the files from DATASUS

# Listar Bases Territoriais
territory.list_tables()

# Exemplo de chamada para baixar bases territoriais:
territory.download('10-base_territorial_out25.zip')

# Baixar dados de agravos SINAN
files=sinan.get_files(dis_code=["SIFA"]) #exemplo sifilis adquirida
sinan.download(files)

# Unificar cada tipo em um único DataFrame
df_sifa = pd.concat([df for _, df in sifa_dados], ignore_index=True)

# Exibir colunas e tipos
df_sifa.columns
df_sifa.head()

output_path = "df_sifa.csv"
df_sifa.to_csv(output_path, index=False)

print(f"df_sifa DataFrame saved to {output_path}")